# Generated by Django 3.0.5 on 2021-06-02 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_review_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Все отзывы'},
        ),
        migrations.RenameField(
            model_name='review',
            old_name='date_created',
            new_name='pub_date',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='review_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='title',
            new_name='title_id',
        ),
    ]
