# Generated by Django 3.0.5 on 2021-06-04 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210604_0031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-pub_date']},
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='date_created',
            new_name='pub_date',
        ),
        migrations.RemoveField(
            model_name='title',
            name='category',
        ),
        migrations.RemoveField(
            model_name='title',
            name='description',
        ),
        migrations.RemoveField(
            model_name='title',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='title',
            name='name',
        ),
        migrations.RemoveField(
            model_name='title',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='title',
            name='year',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
